# Generated by Django 2.1.5 on 2019-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signs',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
