# Generated by Django 2.1.5 on 2019-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piAPI', '0002_signs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signs',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
